{
    # image encoder settings
    encoder_name: 'clip_resnet_large',
    freeze_img_encoder: false,
    
    # train settings 
    batch_size: 256,
    train_steps: 150000,
    lr: 5.0e-5, 
    min_lr: 0.0,
    lr_decay_iters: 300000,
    image_enc_lr: 2.0e-6,
    use_image_embed_layernorm: true,
    image_embed_dropout_prob: 0.1, 
    image_size: 384,
    
    gradient_accumulation_steps: 8,
    zero_stage: 2,
    gradient_clipping: 1.0,

    # dataset / save / load settings
    train_dataset_name: 'coco',
    train_dataset_dir: '/local1/monajati/magma/coco/converted_coco_train/',
    eval_dataset_name: 'coco',
    eval_dataset_dir: '/local1/monajati/magma/coco/converted_coco_val/',
    #eval_dataset_dir: None,
    
    save: "/local1/monajati/magma/checkpoints/few_meta_50per",
    #load: "/home/monajati/main/metaVL/check/xl4",
    #load_optimizer: true,

    eval_every: 100,
}